// Course content: 4 CEFR levels (A2 -> C1), 4 units per level.
// Each unit has: vocabulary, a grammar point with examples, a dialogue
// (listening presented as text, since no audio pipeline), and a quiz.
// unit.id must be globally unique and encodes ordering: "<level>-u<n>"

export const LEVELS = [
  { id: 'A2', title: 'A2 - Elemental', description: 'Consolida las bases: rutinas, pasado, comparaciones y planes.' },
  { id: 'B1', title: 'B1 - Intermedio', description: 'Exprésate con más matices: experiencias, condicionales y opiniones.' },
  { id: 'B2', title: 'B2 - Intermedio alto', description: 'Domina estructuras complejas y vocabulario más preciso.' },
  { id: 'C1', title: 'C1 - Avanzado', description: 'Fluidez, registro formal y matices idiomáticos.' },
];

export const COURSE = [
  // ======================= A2 =======================
  {
    id: 'A2-u1',
    level: 'A2',
    order: 1,
    title: 'Daily Routines',
    subtitle: 'Present simple y adverbios de frecuencia',
    vocabulary: [
      { word: 'to wake up', translation: 'despertarse', example: 'I wake up at 7 am every day.' },
      { word: 'to have breakfast', translation: 'desayunar', example: 'She has breakfast before work.' },
      { word: 'commute', translation: 'trayecto al trabajo', example: 'My commute takes 30 minutes.' },
      { word: 'chores', translation: 'tareas domésticas', example: 'We do the chores on Saturdays.' },
      { word: 'to fall asleep', translation: 'quedarse dormido', example: 'He falls asleep before 11 pm.' },
      { word: 'usually', translation: 'normalmente', example: 'I usually walk to work.' },
      { word: 'rarely', translation: 'rara vez', example: 'She rarely skips breakfast.' },
      { word: 'schedule', translation: 'horario', example: 'My schedule is very busy this week.' },
      { word: 'to get dressed', translation: 'vestirse', example: 'He gets dressed after showering.' },
      { word: 'errand', translation: 'recado', example: 'I need to run an errand this afternoon.' },
    ],
    grammar: {
      title: 'Present Simple + Adverbios de frecuencia',
      explanation:
        "Usamos el Present Simple para hablar de rutinas y hechos habituales. Con 'he/she/it' añadimos -s/-es al verbo. Los adverbios de frecuencia (always, usually, often, sometimes, rarely, never) suelen ir antes del verbo principal, pero después de 'to be'.",
      examples: [
        'I always brush my teeth before bed.',
        'She usually catches the 8 o\'clock bus.',
        'They rarely eat out during the week.',
        'He is never late for meetings.',
        'Do you often work from home?',
      ],
    },
    dialogue: {
      title: 'A Typical Morning',
      lines: [
        { speaker: 'Anna', text: "What time do you usually wake up?" },
        { speaker: 'Marco', text: "I wake up at six thirty and go for a run." },
        { speaker: 'Anna', text: "Wow, that's early! Do you have breakfast before or after?" },
        { speaker: 'Marco', text: "After. I usually have coffee and toast around seven fifteen." },
        { speaker: 'Anna', text: "And how long is your commute?" },
        { speaker: 'Marco', text: "It's short, only twenty minutes by bike." },
      ],
      comprehension: [
        {
          question: 'What does Marco do right after waking up?',
          options: ['He has breakfast', 'He goes for a run', 'He takes the bus', 'He gets dressed'],
          answer: 1,
        },
        {
          question: "How does Marco get to work?",
          options: ['By car', 'By bus', 'By bike', 'On foot'],
          answer: 2,
        },
      ],
    },
    quiz: [
      { type: 'mc', question: "She ___ (work) every day.", options: ['work', 'works', 'working', 'worked'], answer: 1 },
      { type: 'mc', question: "Choose the correct order: 'I ___ ___ late for class.'", options: ['am never', 'never am', 'am not never', 'never not am'], answer: 0 },
      { type: 'mc', question: "'to wake up' means...", options: ['dormirse', 'despertarse', 'vestirse', 'desayunar'], answer: 1 },
      { type: 'fill', question: "They ___ (not/eat) meat.", answer: "don't eat" },
      { type: 'mc', question: "'My ___ takes 30 minutes.' (trayecto)", options: ['schedule', 'commute', 'chore', 'errand'], answer: 1 },
      { type: 'mc', question: "Which sentence is correct?", options: ['She go to work by bus.', 'She goes to work by bus.', 'She going to work by bus.', 'She gone to work by bus.'], answer: 1 },
      { type: 'fill', question: "He ___ (rarely/be) late. (order the adverb correctly)", answer: 'is rarely' },
      { type: 'mc', question: "'errand' means...", options: ['recado', 'horario', 'rutina', 'trayecto'], answer: 0 },
    ],
  },
  {
    id: 'A2-u2',
    level: 'A2',
    order: 2,
    title: 'Talking About the Past',
    subtitle: 'Past simple (regular e irregular)',
    vocabulary: [
      { word: 'yesterday', translation: 'ayer', example: 'I called her yesterday.' },
      { word: 'ago', translation: 'hace (tiempo)', example: 'We moved here two years ago.' },
      { word: 'to arrive', translation: 'llegar', example: 'They arrived late last night.' },
      { word: 'to leave', translation: 'irse / salir', example: 'She left the party early.' },
      { word: 'to buy', translation: 'comprar', example: 'He bought a new laptop.' },
      { word: 'trip', translation: 'viaje', example: 'Our trip to Rome was amazing.' },
      { word: 'to forget', translation: 'olvidar', example: 'I forgot my umbrella at home.' },
      { word: 'suddenly', translation: 'de repente', example: 'Suddenly, it started raining.' },
      { word: 'to break', translation: 'romper', example: 'He broke his phone screen.' },
      { word: 'last week', translation: 'la semana pasada', example: 'We had a test last week.' },
    ],
    grammar: {
      title: 'Past Simple: verbos regulares e irregulares',
      explanation:
        "Los verbos regulares añaden -ed (walk -> walked). Muchos verbos comunes son irregulares y hay que memorizarlos (go -> went, buy -> bought, see -> saw). Para negaciones y preguntas usamos 'did' + infinitivo: 'Did you go?' / 'I didn't go'.",
      examples: [
        'I walked to school yesterday.',
        'She went to Paris last summer.',
        "They didn't finish the project on time.",
        'Did you see the news this morning?',
        'He broke his arm while skiing.',
      ],
    },
    dialogue: {
      title: 'Weekend Trip',
      lines: [
        { speaker: 'Leo', text: "How was your trip to the mountains?" },
        { speaker: 'Sara', text: "It was great! We arrived on Friday night and left on Sunday." },
        { speaker: 'Leo', text: "Did you do any hiking?" },
        { speaker: 'Sara', text: "Yes, we hiked for six hours on Saturday. I was exhausted!" },
        { speaker: 'Leo', text: "Did anything go wrong?" },
        { speaker: 'Sara', text: "Actually, yes — I forgot my hiking boots, so I bought new ones there." },
      ],
      comprehension: [
        { question: 'When did Sara and her friends arrive?', options: ['Saturday morning', 'Friday night', 'Sunday', 'Thursday'], answer: 1 },
        { question: 'What did Sara forget?', options: ['Her phone', 'Her jacket', 'Her hiking boots', 'Her camera'], answer: 2 },
      ],
    },
    quiz: [
      { type: 'mc', question: "Yesterday, I ___ (buy) a new bag.", options: ['buy', 'buyed', 'bought', 'buying'], answer: 2 },
      { type: 'mc', question: "___ you call her last night?", options: ['Do', 'Did', 'Was', 'Were'], answer: 1 },
      { type: 'fill', question: "She ___ (not/arrive) on time.", answer: "didn't arrive" },
      { type: 'mc', question: "'suddenly' means...", options: ['antes', 'de repente', 'hace tiempo', 'ayer'], answer: 1 },
      { type: 'mc', question: "Which is the correct past of 'go'?", options: ['goed', 'went', 'gone', 'going'], answer: 1 },
      { type: 'fill', question: "He ___ (break) his phone yesterday.", answer: 'broke' },
      { type: 'mc', question: "'two years ___' (hace)", options: ['before', 'past', 'ago', 'since'], answer: 2 },
      { type: 'mc', question: "Correct question form:", options: ['Where did you went?', 'Where you did go?', 'Where did you go?', 'Where you go did?'], answer: 2 },
    ],
  },
  {
    id: 'A2-u3',
    level: 'A2',
    order: 3,
    title: 'Comparing Things',
    subtitle: 'Comparativos y superlativos',
    vocabulary: [
      { word: 'cheap / expensive', translation: 'barato / caro', example: 'This phone is cheaper than that one.' },
      { word: 'fast / slow', translation: 'rápido / lento', example: 'The train is faster than the bus.' },
      { word: 'crowded', translation: 'concurrido / lleno de gente', example: 'The market is more crowded on weekends.' },
      { word: 'quiet', translation: 'tranquilo', example: 'This neighborhood is quieter than downtown.' },
      { word: 'convenient', translation: 'práctico / conveniente', example: 'Online shopping is more convenient.' },
      { word: 'similar', translation: 'parecido', example: 'These two cities are quite similar.' },
      { word: 'the best / the worst', translation: 'el mejor / el peor', example: 'This is the best restaurant in town.' },
      { word: 'reliable', translation: 'fiable', example: 'This brand is very reliable.' },
      { word: 'huge', translation: 'enorme', example: 'They live in a huge house.' },
      { word: 'value for money', translation: 'buena relación calidad-precio', example: 'This hotel offers great value for money.' },
    ],
    grammar: {
      title: 'Comparativos y superlativos',
      explanation:
        "Adjetivos cortos: -er/-est (cheap -> cheaper -> the cheapest). Adjetivos largos (3+ sílabas): more/most (expensive -> more expensive -> the most expensive). Irregulares: good -> better -> the best; bad -> worse -> the worst. Usamos 'than' para comparar dos cosas.",
      examples: [
        'This car is cheaper than that one.',
        'Barcelona is more expensive than Seville.',
        'This is the best pizza in the city.',
        'Today is worse than yesterday, the traffic is terrible.',
        'She is as tall as her brother.',
      ],
    },
    dialogue: {
      title: 'Choosing an Apartment',
      lines: [
        { speaker: 'Nora', text: "Which apartment do you prefer, the one downtown or the one near the park?" },
        { speaker: 'Ben', text: "The one near the park is quieter and cheaper." },
        { speaker: 'Nora', text: "But the downtown one is more convenient for work." },
        { speaker: 'Ben', text: "True, but it's also more crowded and noisier at night." },
        { speaker: 'Nora', text: "Good point. I think the park one is the best option overall." },
      ],
      comprehension: [
        { question: 'Which apartment is quieter?', options: ['The downtown one', 'The one near the park', 'Both are the same', 'Neither'], answer: 1 },
        { question: "Why does Nora like the downtown apartment?", options: ['It is cheaper', 'It is quieter', 'It is more convenient for work', 'It is bigger'], answer: 2 },
      ],
    },
    quiz: [
      { type: 'mc', question: "This laptop is ___ (expensive) than mine.", options: ['expensiver', 'more expensive', 'most expensive', 'expensivest'], answer: 1 },
      { type: 'mc', question: "It's ___ (good) restaurant in the city.", options: ['the goodest', 'the better', 'the best', 'more good'], answer: 2 },
      { type: 'fill', question: "This street is ___ (quiet) than the main road.", answer: 'quieter' },
      { type: 'mc', question: "'crowded' means...", options: ['tranquilo', 'concurrido', 'barato', 'fiable'], answer: 1 },
      { type: 'mc', question: "Choose the irregular comparative of 'bad':", options: ['badder', 'more bad', 'worse', 'baddest'], answer: 2 },
      { type: 'fill', question: "She is as ___ (tall) as her sister.", answer: 'tall' },
      { type: 'mc', question: "'value for money' means...", options: ['dinero fácil', 'buena relación calidad-precio', 'precio alto', 'sin valor'], answer: 1 },
      { type: 'mc', question: "Correct superlative of 'big':", options: ['the biggest', 'the bigest', 'the more big', 'the most big'], answer: 0 },
    ],
  },
  {
    id: 'A2-u4',
    level: 'A2',
    order: 4,
    title: 'Future Plans',
    subtitle: "'going to' y 'will'",
    vocabulary: [
      { word: 'to plan', translation: 'planear', example: "I'm planning to visit Japan next year." },
      { word: 'to move (house)', translation: 'mudarse', example: "We're going to move to a bigger flat." },
      { word: 'to expect', translation: 'esperar (que algo pase)', example: 'I expect it will rain tomorrow.' },
      { word: 'likely', translation: 'probable', example: "It's likely to rain this weekend." },
      { word: 'to decide', translation: 'decidir', example: 'Have you decided where to go?' },
      { word: 'appointment', translation: 'cita', example: 'I have a dentist appointment tomorrow.' },
      { word: 'career', translation: 'carrera profesional', example: 'She wants to build a career in design.' },
      { word: 'to promise', translation: 'prometer', example: "I promise I'll call you tonight." },
      { word: 'eventually', translation: 'finalmente / con el tiempo', example: 'Eventually, they found a solution.' },
      { word: 'in advance', translation: 'con antelación', example: 'Book your tickets in advance.' },
    ],
    grammar: {
      title: "'going to' vs 'will'",
      explanation:
        "Usamos 'going to' para planes ya decididos e intenciones ('I'm going to study tonight'). Usamos 'will' para decisiones espontáneas, predicciones sin evidencia y promesas ('I think it will be sunny', 'I'll help you'). Ambos se usan para el futuro, pero con matices distintos.",
      examples: [
        "I'm going to start a new job next month.",
        'I think she will love this gift.',
        "Wait, I'll open the door for you!",
        "They aren't going to travel this summer.",
        'Will you be at the meeting tomorrow?',
      ],
    },
    dialogue: {
      title: 'Planning the Weekend',
      lines: [
        { speaker: 'Julia', text: "What are you going to do this weekend?" },
        { speaker: 'Tom', text: "I'm going to visit my parents on Saturday." },
        { speaker: 'Julia', text: "Nice! And on Sunday?" },
        { speaker: 'Tom', text: "I'm not sure yet. Maybe I'll go for a hike if the weather is good." },
        { speaker: 'Julia', text: "I think it will rain, actually." },
        { speaker: 'Tom', text: "Oh no. Well, then I'll just stay home and relax." },
      ],
      comprehension: [
        { question: 'What is Tom doing on Saturday?', options: ['Going for a hike', 'Visiting his parents', 'Staying home', 'Working'], answer: 1 },
        { question: "What does Tom decide if it rains?", options: ['Go hiking anyway', 'Visit his parents again', 'Stay home and relax', 'Go to Julia\'s house'], answer: 2 },
      ],
    },
    quiz: [
      { type: 'mc', question: "We ___ (already decided) ___ move next year.", options: ["are going to", "will", "are will", "going will"], answer: 0 },
      { type: 'mc', question: "Spontaneous decision: 'It's cold in here.' 'Okay, I ___ close the window.'", options: ['am going to', 'will', 'am close to', 'go to'], answer: 1 },
      { type: 'fill', question: "I promise I ___ (call) you tonight.", answer: "will call" },
      { type: 'mc', question: "'in advance' means...", options: ['con retraso', 'con antelación', 'a veces', 'nunca'], answer: 1 },
      { type: 'mc', question: "'to move house' means...", options: ['mudarse', 'viajar', 'decidir', 'prometer'], answer: 0 },
      { type: 'fill', question: "Look at those clouds! It ___ (rain) soon.", answer: "is going to rain" },
      { type: 'mc', question: "'likely' means...", options: ['imposible', 'probable', 'seguro', 'raro'], answer: 1 },
      { type: 'mc', question: "Correct question:", options: ['Will you be at the party?', 'You will be at the party?', 'Will be you at the party?', 'Be will you at the party?'], answer: 0 },
    ],
  },

  // ======================= B1 =======================
  {
    id: 'B1-u1',
    level: 'B1',
    order: 1,
    title: 'Life Experiences',
    subtitle: 'Present Perfect vs Past Simple',
    vocabulary: [
      { word: 'to have been to', translation: 'haber estado en', example: "I've been to Japan twice." },
      { word: 'achievement', translation: 'logro', example: 'Graduating was a big achievement for her.' },
      { word: 'so far', translation: 'hasta ahora', example: "So far, we haven't had any problems." },
      { word: 'recently', translation: 'recientemente', example: 'I have recently changed jobs.' },
      { word: 'to overcome', translation: 'superar', example: 'He overcame his fear of public speaking.' },
      { word: 'milestone', translation: 'hito', example: 'Turning thirty felt like a milestone.' },
      { word: 'never before', translation: 'nunca antes', example: "I've never before tried sushi." },
      { word: 'just', translation: 'justo / acabar de', example: "I've just finished my homework." },
      { word: 'yet', translation: 'todavía / ya (en negativas/preguntas)', example: "Have you finished yet?" },
      { word: 'to accomplish', translation: 'lograr / conseguir', example: 'She accomplished all her goals this year.' },
    ],
    grammar: {
      title: 'Present Perfect vs Past Simple',
      explanation:
        "Present Perfect (have/has + participio) conecta el pasado con el presente y se usa cuando el momento no es específico ('I have visited London'). Past Simple se usa con un momento específico del pasado ('I visited London in 2019'). Palabras clave del Present Perfect: ever, never, already, yet, just, so far, recently. Palabras clave del Past Simple: yesterday, last year, in 2020, ago.",
      examples: [
        "I have visited Italy three times.",
        "I visited Italy in 2018.",
        "She hasn't finished the report yet.",
        "Have you ever tried Thai food?",
        "We just arrived at the hotel.",
      ],
    },
    dialogue: {
      title: 'Job Interview',
      lines: [
        { speaker: 'Interviewer', text: "Have you ever managed a team before?" },
        { speaker: 'Candidate', text: "Yes, I've managed a team of five people for two years." },
        { speaker: 'Interviewer', text: "Interesting. When did you start that role?" },
        { speaker: 'Candidate', text: "I started in 2022 and I left the company last month." },
        { speaker: 'Interviewer', text: "What's your biggest achievement so far?" },
        { speaker: 'Candidate', text: "I've just finished leading a project that increased sales by 20%." },
      ],
      comprehension: [
        { question: 'How long did the candidate manage the team?', options: ['One year', 'Two years', 'Five years', 'It’s not mentioned'], answer: 1 },
        { question: 'What did the candidate recently finish?', options: ['A university degree', 'A project that increased sales', 'A job interview', 'A team of five'], answer: 1 },
      ],
    },
    quiz: [
      { type: 'mc', question: "I ___ (see) that film already.", options: ['saw', 'have seen', 'see', 'seeing'], answer: 1 },
      { type: 'mc', question: "She ___ (visit) Rome in 2019.", options: ['has visited', 'visited', 'visits', 'was visit'], answer: 1 },
      { type: 'fill', question: "___ you ever ___ (be) to Australia?", answer: "have...been" },
      { type: 'mc', question: "'so far' means...", options: ['antes de todo', 'hasta ahora', 'la próxima vez', 'nunca'], answer: 1 },
      { type: 'mc', question: "Choose the correct sentence:", options: ["I have finished it yesterday.", "I finished it yesterday.", "I finish it yesterday.", "I have finish it yesterday."], answer: 1 },
      { type: 'fill', question: "We ___ just ___ (arrive).", answer: 'have...arrived' },
      { type: 'mc', question: "'to overcome' means...", options: ['evitar', 'superar', 'olvidar', 'empezar'], answer: 1 },
      { type: 'mc', question: "Which needs Present Perfect?", options: ['... in 2015.', '... last week.', '... never before.', '... yesterday morning.'], answer: 2 },
    ],
  },
  {
    id: 'B1-u2',
    level: 'B1',
    order: 2,
    title: 'Real Possibilities',
    subtitle: 'First Conditional',
    vocabulary: [
      { word: 'unless', translation: 'a menos que', example: "You won't pass unless you study." },
      { word: 'to miss (a deadline)', translation: 'perder / no llegar a', example: "We'll miss the deadline if we don't hurry." },
      { word: 'consequence', translation: 'consecuencia', example: 'Every action has a consequence.' },
      { word: 'to postpone', translation: 'posponer', example: "If it rains, we'll postpone the trip." },
      { word: 'in case', translation: 'por si acaso', example: "Take an umbrella in case it rains." },
      { word: 'as long as', translation: 'siempre que', example: "You can stay as long as you're quiet." },
      { word: 'to risk', translation: 'arriesgar', example: "If you don't wear a helmet, you risk an injury." },
      { word: 'outcome', translation: 'resultado', example: "The outcome will depend on the weather." },
      { word: 'to warn', translation: 'advertir', example: "I'll warn you if there's a problem." },
      { word: 'provided that', translation: 'siempre y cuando', example: "You can go out, provided that you finish your homework." },
    ],
    grammar: {
      title: 'First Conditional',
      explanation:
        "Se usa para hablar de situaciones futuras reales o posibles: If + present simple, ... will + infinitivo. 'If it rains, we will stay home.' También se puede usar 'unless' (= if not), 'as long as' y 'provided that' en lugar de 'if'.",
      examples: [
        "If you study hard, you will pass the exam.",
        "Unless we leave now, we will miss the train.",
        "I'll call you if I have any news.",
        "As long as you finish on time, it's fine.",
        "What will you do if it rains?",
      ],
    },
    dialogue: {
      title: 'Planning a Trip',
      lines: [
        { speaker: 'Diego', text: "If the weather is good, we'll go hiking on Saturday." },
        { speaker: 'Elena', text: "And if it rains?" },
        { speaker: 'Diego', text: "Unless it stops by noon, we'll postpone it to Sunday." },
        { speaker: 'Elena', text: "Okay. I'll bring a raincoat in case." },
        { speaker: 'Diego', text: "Good idea. As long as we check the forecast tonight, we'll be fine." },
      ],
      comprehension: [
        { question: "What will they do if the weather is good?", options: ['Stay home', 'Go hiking', 'Go to the beach', 'Postpone the trip'], answer: 1 },
        { question: 'What will Elena bring, just in case?', options: ['An umbrella', 'A map', 'A raincoat', 'Sunscreen'], answer: 2 },
      ],
    },
    quiz: [
      { type: 'mc', question: "If it ___ (rain), we will cancel the picnic.", options: ['rains', 'will rain', 'rained', 'rain'], answer: 0 },
      { type: 'mc', question: "Unless you hurry, you ___ (miss) the bus.", options: ['miss', 'will miss', 'missed', 'missing'], answer: 1 },
      { type: 'fill', question: "If she calls, I ___ (tell) you.", answer: 'will tell' },
      { type: 'mc', question: "'unless' is closest in meaning to...", options: ['if', 'if not', 'even if', 'although'], answer: 1 },
      { type: 'mc', question: "'to postpone' means...", options: ['adelantar', 'cancelar', 'posponer', 'empezar'], answer: 2 },
      { type: 'fill', question: "___ (provided) you finish on time, it's fine.", answer: 'provided that' },
      { type: 'mc', question: "'outcome' means...", options: ['resultado', 'consecuencia negativa', 'riesgo', 'advertencia'], answer: 0 },
      { type: 'mc', question: "Correct sentence:", options: ['If I will see him, I will tell him.', 'If I see him, I will tell him.', 'If I see him, I tell him.', 'If I saw him, I will tell him.'], answer: 1 },
    ],
  },
  {
    id: 'B1-u3',
    level: 'B1',
    order: 3,
    title: 'Giving Opinions',
    subtitle: 'Modal verbs: should, might, must',
    vocabulary: [
      { word: 'in my opinion', translation: 'en mi opinión', example: 'In my opinion, this policy is unfair.' },
      { word: 'to agree / disagree', translation: 'estar de acuerdo / en desacuerdo', example: 'I disagree with that decision.' },
      { word: 'obligation', translation: 'obligación', example: 'Wearing a seatbelt is a legal obligation.' },
      { word: 'probably', translation: 'probablemente', example: "It's probably going to rain later." },
      { word: 'to assume', translation: 'suponer', example: "I assume you've already read the email." },
      { word: 'point of view', translation: 'punto de vista', example: 'From my point of view, it makes sense.' },
      { word: 'to convince', translation: 'convencer', example: 'She convinced me to try the new restaurant.' },
      { word: 'to be worth it', translation: 'valer la pena', example: 'The trip was long, but it was worth it.' },
      { word: 'debatable', translation: 'discutible', example: "That's a debatable statement." },
      { word: 'certainly', translation: 'ciertamente', example: 'It is certainly a difficult decision.' },
    ],
    grammar: {
      title: "Modal verbs: should, might, must (opinión y probabilidad)",
      explanation:
        "'Should' expresa consejo u opinión sobre lo correcto ('You should apologize'). 'Must' expresa obligación fuerte o una deducción casi segura ('You must be tired'). 'Might/may' expresan posibilidad ('It might rain later'). Todos van seguidos de infinitivo sin 'to'.",
      examples: [
        "You should try the new restaurant downtown.",
        "This must be the best decision we've made.",
        "It might rain, so take an umbrella.",
        "In my opinion, they should invest more in education.",
        "He must be exhausted after that trip.",
      ],
    },
    dialogue: {
      title: 'Debate Club',
      lines: [
        { speaker: 'Host', text: "Do you think remote work should be the norm?" },
        { speaker: 'Priya', text: "In my opinion, companies should offer flexibility, but it depends on the job." },
        { speaker: 'Host', text: "What about you, Sam?" },
        { speaker: 'Sam', text: "I disagree a bit. Some teams must meet in person to collaborate well." },
        { speaker: 'Priya', text: "That's fair, but it might work with a hybrid model." },
        { speaker: 'Sam', text: "True, a hybrid approach could convince both sides." },
      ],
      comprehension: [
        { question: "What does Priya think companies should offer?", options: ['Higher salaries', 'Flexibility', 'Longer hours', 'More meetings'], answer: 1 },
        { question: "What compromise do they mention?", options: ['Fully remote work', 'Fully in-person work', 'A hybrid model', 'No work at all'], answer: 2 },
      ],
    },
    quiz: [
      { type: 'mc', question: "You ___ (should) apologize to her.", options: ['must', 'should', 'might', 'can'], answer: 1 },
      { type: 'mc', question: "It ___ (possibility) rain later.", options: ['must', 'should', 'might', 'has to'], answer: 2 },
      { type: 'fill', question: "He ___ (obligación fuerte) finish the report today.", answer: 'must' },
      { type: 'mc', question: "'in my opinion' means...", options: ['sin duda', 'en mi opinión', 'por ejemplo', 'de hecho'], answer: 1 },
      { type: 'mc', question: "'to be worth it' means...", options: ['valer la pena', 'no importar', 'ser gratis', 'ser injusto'], answer: 0 },
      { type: 'fill', question: "I ___ (assume) you already know the news.", answer: 'assume' },
      { type: 'mc', question: "'debatable' means...", options: ['indiscutible', 'discutible', 'obligatorio', 'probable'], answer: 1 },
      { type: 'mc', question: "Strong deduction: 'You've been traveling all day, you ___ be tired.'", options: ['might', 'must', 'should', 'could'], answer: 1 },
    ],
  },
  {
    id: 'B1-u4',
    level: 'B1',
    order: 4,
    title: 'Describing Places',
    subtitle: 'Relative clauses (who, which, where, that)',
    vocabulary: [
      { word: 'located', translation: 'ubicado', example: 'The hotel is located near the beach.' },
      { word: 'scenery', translation: 'paisaje', example: 'The scenery in the mountains is breathtaking.' },
      { word: 'landmark', translation: 'lugar emblemático', example: 'The tower is a famous landmark.' },
      { word: 'to be worth visiting', translation: 'merecer la pena visitar', example: 'This museum is worth visiting.' },
      { word: 'atmosphere', translation: 'ambiente', example: 'The café has a cozy atmosphere.' },
      { word: 'off the beaten path', translation: 'fuera de lo común / poco turístico', example: 'We found a beach off the beaten path.' },
      { word: 'crowded', translation: 'concurrido', example: 'The market gets crowded on weekends.' },
      { word: 'view', translation: 'vista', example: 'The apartment has a great view of the sea.' },
      { word: 'to stand out', translation: 'destacar', example: 'This building stands out because of its architecture.' },
      { word: 'surroundings', translation: 'alrededores', example: 'The surroundings are very peaceful.' },
    ],
    grammar: {
      title: 'Relative Clauses',
      explanation:
        "Usamos 'who' para personas, 'which' para cosas, 'where' para lugares y 'that' para personas o cosas (más informal). Las oraciones de relativo especificativas no llevan comas: 'The city where I was born is small.' Las explicativas sí llevan comas y dan información extra: 'Paris, which is the capital of France, is beautiful.'",
      examples: [
        "This is the restaurant where we had our first date.",
        "The woman who lives next door is a doctor.",
        "I lost the book that you lent me.",
        "Kyoto, which used to be the capital, has amazing temples.",
        "That's the reason why I moved here.",
      ],
    },
    dialogue: {
      title: 'Travel Recommendations',
      lines: [
        { speaker: 'Ines', text: "Do you know a place where we could relax this weekend?" },
        { speaker: 'Carlos', text: "There's a village that not many tourists visit, off the beaten path." },
        { speaker: 'Ines', text: "That sounds perfect. What's it like?" },
        { speaker: 'Carlos', text: "It's a place which has amazing scenery and a really calm atmosphere." },
        { speaker: 'Ines', text: "Is there a landmark that's worth visiting?" },
        { speaker: 'Carlos', text: "Yes, an old church that stands out on the hill above the village." },
      ],
      comprehension: [
        { question: 'What kind of place does Carlos recommend?', options: ['A crowded city', 'A village off the beaten path', 'A famous beach', 'A busy market'], answer: 1 },
        { question: 'What landmark does he mention?', options: ['A castle', 'A museum', 'An old church', 'A lighthouse'], answer: 2 },
      ],
    },
    quiz: [
      { type: 'mc', question: "This is the house ___ I grew up.", options: ['who', 'which', 'where', 'whose'], answer: 2 },
      { type: 'mc', question: "The man ___ called you is my brother.", options: ['which', 'who', 'where', 'whom'], answer: 1 },
      { type: 'fill', question: "I found the keys ___ (that/which) I lost yesterday.", answer: 'that' },
      { type: 'mc', question: "'landmark' means...", options: ['lugar emblemático', 'ambiente', 'alrededores', 'paisaje'], answer: 0 },
      { type: 'mc', question: "'to stand out' means...", options: ['pasar desapercibido', 'destacar', 'desaparecer', 'ubicarse'], answer: 1 },
      { type: 'fill', question: "'off the beaten ___'", answer: 'path' },
      { type: 'mc', question: "'scenery' means...", options: ['paisaje', 'edificio', 'multitud', 'ruta'], answer: 0 },
      { type: 'mc', question: "Correct: 'Paris, ___ is the capital of France, is beautiful.'", options: ['that', 'which', 'who', 'where'], answer: 1 },
    ],
  },

  // ======================= B2 =======================
  {
    id: 'B2-u1',
    level: 'B2',
    order: 1,
    title: 'Hypothetical Situations',
    subtitle: 'Second Conditional',
    vocabulary: [
      { word: 'if I were you', translation: 'si yo fuera tú', example: 'If I were you, I would accept the offer.' },
      { word: 'to imagine', translation: 'imaginar', example: 'Imagine if we won the lottery.' },
      { word: 'unlikely', translation: 'poco probable', example: "It's unlikely that he would agree." },
      { word: 'to afford', translation: 'permitirse (económicamente)', example: "If I had more money, I'd afford a bigger house." },
      { word: 'to regret', translation: 'arrepentirse', example: 'I would regret not trying.' },
      { word: 'wealthy', translation: 'adinerado', example: 'If she were wealthy, she would travel more.' },
      { word: 'to pretend', translation: 'fingir', example: "Let's pretend we were on a deserted island." },
      { word: 'circumstances', translation: 'circunstancias', example: 'Under different circumstances, I would say yes.' },
      { word: 'realistic', translation: 'realista', example: "That plan isn't very realistic." },
      { word: 'to cope with', translation: 'lidiar con', example: "I don't know how I'd cope with that pressure." },
    ],
    grammar: {
      title: 'Second Conditional',
      explanation:
        "Se usa para situaciones hipotéticas o poco probables en presente/futuro: If + past simple, ... would + infinitivo. 'If I won the lottery, I would travel the world.' Con 'be', se prefiere 'were' para todas las personas en registro más formal ('If I were you...').",
      examples: [
        "If I had more time, I would learn another language.",
        "If she were the manager, she would change the schedule.",
        "What would you do if you lost your job?",
        "I wouldn't worry about it if I were you.",
        "If they offered me the job, I would take it.",
      ],
    },
    dialogue: {
      title: 'What If...',
      lines: [
        { speaker: 'Maya', text: "If you could live anywhere, where would you live?" },
        { speaker: 'Owen', text: "I'd probably live near the coast if I could afford it." },
        { speaker: 'Maya', text: "What would you do if you didn't have to work?" },
        { speaker: 'Owen', text: "I'd travel a lot and maybe write a book." },
        { speaker: 'Maya', text: "If I were you, I'd start writing now, even part-time." },
        { speaker: 'Owen', text: "You're right. I'd regret it if I never tried." },
      ],
      comprehension: [
        { question: "Where would Owen live if he could afford it?", options: ['In the mountains', 'Near the coast', 'In the city', 'Abroad'], answer: 1 },
        { question: "What does Maya suggest Owen do?", options: ['Quit his job now', 'Start writing part-time', 'Move immediately', 'Save more money'], answer: 1 },
      ],
    },
    quiz: [
      { type: 'mc', question: "If I ___ (have) more money, I would travel more.", options: ['have', 'had', 'would have', 'having'], answer: 1 },
      { type: 'mc', question: "If she ___ (be) here, she would help us.", options: ['is', 'was', 'were', 'be'], answer: 2 },
      { type: 'fill', question: "What ___ you ___ (do) if you won the lottery?", answer: 'would...do' },
      { type: 'mc', question: "'unlikely' means...", options: ['probable', 'poco probable', 'seguro', 'imposible'], answer: 1 },
      { type: 'mc', question: "'to afford' means...", options: ['permitirse pagar', 'ofrecer', 'ahorrar', 'gastar'], answer: 0 },
      { type: 'fill', question: "I wouldn't worry if I ___ (be) you.", answer: 'were' },
      { type: 'mc', question: "'to regret' means...", options: ['celebrar', 'arrepentirse', 'olvidar', 'fingir'], answer: 1 },
      { type: 'mc', question: "Correct sentence:", options: ["If I would be rich, I travel.", "If I was rich, I will travel.", "If I were rich, I would travel.", "If I am rich, I would travel."], answer: 2 },
    ],
  },
  {
    id: 'B2-u2',
    level: 'B2',
    order: 2,
    title: 'Reporting What Others Said',
    subtitle: 'Reported speech',
    vocabulary: [
      { word: 'to claim', translation: 'afirmar', example: 'He claimed that he was innocent.' },
      { word: 'to mention', translation: 'mencionar', example: 'She mentioned that she was moving abroad.' },
      { word: 'to deny', translation: 'negar', example: 'He denied breaking the vase.' },
      { word: 'to admit', translation: 'admitir', example: 'She admitted she had made a mistake.' },
      { word: 'to point out', translation: 'señalar', example: 'He pointed out that the report had an error.' },
      { word: 'allegedly', translation: 'presuntamente', example: 'He allegedly stole the documents.' },
      { word: 'to insist', translation: 'insistir', example: 'She insisted that she was right.' },
      { word: 'statement', translation: 'declaración', example: 'The company released an official statement.' },
      { word: 'to complain', translation: 'quejarse', example: 'The neighbors complained about the noise.' },
      { word: 'to reveal', translation: 'revelar', example: 'The report revealed new information.' },
    ],
    grammar: {
      title: 'Reported Speech (estilo indirecto)',
      explanation:
        "Al reportar lo que alguien dijo, normalmente retrocedemos un tiempo verbal: present simple -> past simple, present perfect -> past perfect, will -> would, can -> could. También cambian los pronombres y expresiones de tiempo/lugar ('today' -> 'that day', 'tomorrow' -> 'the next day').",
      examples: [
        "\"I am tired,\" she said. -> She said (that) she was tired.",
        "\"I will call you,\" he said. -> He said he would call me.",
        "\"I have finished,\" she said. -> She said she had finished.",
        "\"I can help,\" he said. -> He said he could help.",
        "\"I saw them yesterday,\" she said. -> She said she had seen them the day before.",
      ],
    },
    dialogue: {
      title: 'Office Gossip',
      lines: [
        { speaker: 'Rita', text: "Did you hear? Tom said he was leaving the company." },
        { speaker: 'Sam', text: "Really? He told me he loved his job last week." },
        { speaker: 'Rita', text: "Well, he mentioned that he had received a better offer." },
        { speaker: 'Sam', text: "Did he say when he would leave?" },
        { speaker: 'Rita', text: "He said he would give his notice by Friday." },
        { speaker: 'Sam', text: "Wow. He also admitted he had been looking for months." },
      ],
      comprehension: [
        { question: 'What did Tom say he had received?', options: ['A promotion', 'A better offer', 'A warning', 'A vacation'], answer: 1 },
        { question: "By when did Tom say he would give notice?", options: ['Monday', 'Wednesday', 'Friday', 'The next month'], answer: 2 },
      ],
    },
    quiz: [
      { type: 'mc', question: "\"I am busy,\" she said. -> She said she ___ busy.", options: ['is', 'was', 'be', 'has been'], answer: 1 },
      { type: 'mc', question: "\"I will call,\" he said. -> He said he ___ call.", options: ['will', 'would', 'can', 'could'], answer: 1 },
      { type: 'fill', question: "\"I have finished,\" she said. -> She said she ___ finished.", answer: 'had' },
      { type: 'mc', question: "'to deny' means...", options: ['admitir', 'negar', 'revelar', 'insistir'], answer: 1 },
      { type: 'mc', question: "'allegedly' means...", options: ['seguramente', 'presuntamente', 'nunca', 'obviamente'], answer: 1 },
      { type: 'fill', question: "\"I saw them yesterday,\" she said. -> She said she had seen them ___ day before.", answer: 'the' },
      { type: 'mc', question: "'to point out' means...", options: ['ignorar', 'señalar', 'esconder', 'negar'], answer: 1 },
      { type: 'mc', question: "\"I can help,\" he said. -> He said he ___ help.", options: ['can', 'could', 'will', 'would'], answer: 1 },
    ],
  },
  {
    id: 'B2-u3',
    level: 'B2',
    order: 3,
    title: 'Getting Things Done',
    subtitle: 'Passive voice',
    vocabulary: [
      { word: 'to be built', translation: 'ser construido', example: 'The bridge was built in 1990.' },
      { word: 'to be released', translation: 'ser lanzado/publicado', example: 'The album was released last month.' },
      { word: 'to be discovered', translation: 'ser descubierto', example: 'Penicillin was discovered by accident.' },
      { word: 'to be affected', translation: 'verse afectado', example: 'The region was affected by the storm.' },
      { word: 'to be handled', translation: 'ser gestionado', example: 'The complaint was handled quickly.' },
      { word: 'to be delayed', translation: 'sufrir un retraso', example: 'The flight was delayed by two hours.' },
      { word: 'to be repaired', translation: 'ser reparado', example: 'The car was repaired yesterday.' },
      { word: 'to be launched', translation: 'ser lanzado (producto/misión)', example: 'The satellite will be launched next week.' },
      { word: 'to be updated', translation: 'ser actualizado', example: 'The app was updated last night.' },
      { word: 'to be carried out', translation: 'ser llevado a cabo', example: 'The study was carried out by researchers.' },
    ],
    grammar: {
      title: 'Passive Voice',
      explanation:
        "Se usa la voz pasiva cuando el foco está en la acción o el receptor, no en quién la hace: be + participio. 'The report was written by the team.' Es muy común en contextos formales, científicos y de noticias. Con 'by' indicamos el agente solo si es relevante.",
      examples: [
        "The Eiffel Tower was built in 1889.",
        "This software is used by millions of people.",
        "The results will be announced tomorrow.",
        "Mistakes were made during the process.",
        "The new policy has been approved by the board.",
      ],
    },
    dialogue: {
      title: 'Product Launch',
      lines: [
        { speaker: 'Lucas', text: "When will the new phone be released?" },
        { speaker: 'Nadia', text: "It's going to be launched next month, I think." },
        { speaker: 'Lucas', text: "Has the design been finalized yet?" },
        { speaker: 'Nadia', text: "Yes, it was approved last week by the design team." },
        { speaker: 'Lucas', text: "And the marketing campaign?" },
        { speaker: 'Nadia', text: "It's already being handled by an external agency." },
      ],
      comprehension: [
        { question: 'When will the phone be launched?', options: ['This week', 'Next month', 'Next year', "It's not mentioned"], answer: 1 },
        { question: 'Who is handling the marketing campaign?', options: ['Nadia', 'Lucas', 'The design team', 'An external agency'], answer: 3 },
      ],
    },
    quiz: [
      { type: 'mc', question: "The bridge ___ (build) in 1990.", options: ['built', 'was built', 'is build', 'has build'], answer: 1 },
      { type: 'mc', question: "This app ___ (use) by millions of people.", options: ['uses', 'is used', 'used', 'is using'], answer: 1 },
      { type: 'fill', question: "The results will ___ (announce) tomorrow.", answer: 'be announced' },
      { type: 'mc', question: "'to be delayed' means...", options: ['adelantarse', 'sufrir un retraso', 'ser cancelado', 'ser aprobado'], answer: 1 },
      { type: 'mc', question: "'to be carried out' means...", options: ['ser llevado a cabo', 'ser cargado', 'ser transportado', 'ser rechazado'], answer: 0 },
      { type: 'fill', question: "Mistakes ___ (make) during the process.", answer: 'were made' },
      { type: 'mc', question: "'to be launched' means...", options: ['ser lanzado', 'ser reparado', 'ser actualizado', 'ser descubierto'], answer: 0 },
      { type: 'mc', question: "Correct passive: 'The email...'", options: ['sent yesterday.', 'was sent yesterday.', 'is sending yesterday.', 'sends yesterday.'], answer: 1 },
    ],
  },
  {
    id: 'B2-u4',
    level: 'B2',
    order: 4,
    title: 'Regrets and Advice About the Past',
    subtitle: 'Third Conditional & wish',
    vocabulary: [
      { word: 'to regret', translation: 'arrepentirse', example: "I regret not studying abroad." },
      { word: 'in hindsight', translation: 'en retrospectiva', example: 'In hindsight, we should have left earlier.' },
      { word: 'to have avoided', translation: 'haber evitado', example: 'We could have avoided the mistake.' },
      { word: 'if only', translation: 'ojalá', example: "If only I had listened to her advice." },
      { word: 'consequence', translation: 'consecuencia', example: 'That decision had serious consequences.' },
      { word: 'to blame', translation: 'culpar', example: "Don't blame yourself for what happened." },
      { word: 'opportunity', translation: 'oportunidad', example: 'I missed a great opportunity.' },
      { word: 'lesson learned', translation: 'lección aprendida', example: 'It was a hard lesson learned.' },
      { word: 'to look back on', translation: 'mirar atrás / recordar', example: 'Looking back on it, it was worth it.' },
      { word: 'turning point', translation: 'punto de inflexión', example: 'That year was a turning point in my career.' },
    ],
    grammar: {
      title: 'Third Conditional & wish + past perfect',
      explanation:
        "El Third Conditional habla de situaciones hipotéticas en el pasado que no ocurrieron: If + past perfect, ... would have + participio. 'If I had studied, I would have passed.' 'Wish + past perfect' expresa arrepentimiento: 'I wish I had studied harder.'",
      examples: [
        "If I had known, I would have told you.",
        "She wouldn't have missed the flight if she had left earlier.",
        "I wish I had taken that job offer.",
        "If only we had booked the tickets in advance.",
        "He would have passed if he had studied more.",
      ],
    },
    dialogue: {
      title: 'Looking Back',
      lines: [
        { speaker: 'Grace', text: "If I had known how hard it would be, I might not have started." },
        { speaker: 'Ivan', text: "Really? I thought you loved the project." },
        { speaker: 'Grace', text: "I do, but I wish I had planned the budget better." },
        { speaker: 'Ivan', text: "In hindsight, we all could have avoided that problem." },
        { speaker: 'Grace', text: "True. If only we had asked for more time at the start." },
        { speaker: 'Ivan', text: "Well, it's a lesson learned for the next one." },
      ],
      comprehension: [
        { question: 'What does Grace regret?', options: ['Starting the project', 'Not planning the budget better', 'Asking for more time', 'Not loving the project'], answer: 1 },
        { question: "What do they agree was a turning point?", options: ['Asking for more time', 'The budget problem', 'Finishing early', 'Hiring more staff'], answer: 1 },
      ],
    },
    quiz: [
      { type: 'mc', question: "If I ___ (know), I would have told you.", options: ['knew', 'had known', 'know', 'would know'], answer: 1 },
      { type: 'mc', question: "She would have passed if she ___ (study) more.", options: ['studied', 'had studied', 'studies', 'would study'], answer: 1 },
      { type: 'fill', question: "I wish I ___ (take) that job offer.", answer: 'had taken' },
      { type: 'mc', question: "'in hindsight' means...", options: ['en el futuro', 'en retrospectiva', 'de repente', 'sin razón'], answer: 1 },
      { type: 'mc', question: "'turning point' means...", options: ['punto de inflexión', 'punto final', 'error grave', 'oportunidad perdida'], answer: 0 },
      { type: 'fill', question: "If only we ___ (book) the tickets earlier.", answer: 'had booked' },
      { type: 'mc', question: "'to blame' means...", options: ['felicitar', 'culpar', 'perdonar', 'ignorar'], answer: 1 },
      { type: 'mc', question: "Correct third conditional:", options: ["If I had more time, I would have finished.", "If I had had more time, I would have finished.", "If I have more time, I would have finished.", "If I had more time, I will finish."], answer: 1 },
    ],
  },

  // ======================= C1 =======================
  {
    id: 'C1-u1',
    level: 'C1',
    order: 1,
    title: 'Nuanced Arguments',
    subtitle: 'Inversion for emphasis',
    vocabulary: [
      { word: 'seldom', translation: 'raramente', example: 'Seldom have I seen such dedication.' },
      { word: 'to concede', translation: 'reconocer / conceder', example: 'I concede that the argument has merit.' },
      { word: 'notwithstanding', translation: 'no obstante', example: 'Notwithstanding the risks, they proceeded.' },
      { word: 'to undermine', translation: 'socavar', example: 'This decision undermines public trust.' },
      { word: 'compelling', translation: 'convincente', example: 'She made a compelling case for reform.' },
      { word: 'to reconcile', translation: 'conciliar', example: 'It is hard to reconcile these two views.' },
      { word: 'sweeping statement', translation: 'afirmación generalizada', example: "That's a rather sweeping statement." },
      { word: 'to hinge on', translation: 'depender de', example: 'The outcome hinges on public opinion.' },
      { word: 'nuance', translation: 'matiz', example: 'The debate lost all nuance on social media.' },
      { word: 'to substantiate', translation: 'fundamentar', example: 'You need evidence to substantiate that claim.' },
    ],
    grammar: {
      title: 'Inversion for Emphasis',
      explanation:
        "En registro formal/literario, ciertos adverbios negativos o restrictivos al inicio de la frase provocan inversión sujeto-verbo (como en las preguntas): Seldom, Rarely, Never, Not only, No sooner, Little, Under no circumstances. 'Never have I seen such chaos.' 'Not only did she win, but she also broke the record.'",
      examples: [
        "Seldom have I encountered such a compelling argument.",
        "Not only did he arrive late, but he also forgot the documents.",
        "Under no circumstances should you sign without reading it.",
        "Little did she know that the deal would fall through.",
        "No sooner had they left than it started raining.",
      ],
    },
    dialogue: {
      title: 'A Formal Debate',
      lines: [
        { speaker: 'Moderator', text: "Do you concede that the policy has had some benefits?" },
        { speaker: 'Dr. Lang', text: "Notwithstanding a few positive outcomes, the overall impact has been negative." },
        { speaker: 'Moderator', text: "That's a rather sweeping statement, isn't it?" },
        { speaker: 'Dr. Lang', text: "Not only has unemployment risen, but public trust has also declined." },
        { speaker: 'Moderator', text: "Can you substantiate that with data?" },
        { speaker: 'Dr. Lang', text: "Seldom have I seen a report with such compelling figures." },
      ],
      comprehension: [
        { question: 'What does Dr. Lang concede?', options: ['Nothing at all', 'A few positive outcomes', 'That the policy is perfect', 'That data is unnecessary'], answer: 1 },
        { question: 'What two things does Dr. Lang say happened?', options: ['Unemployment fell and trust rose', 'Unemployment rose and trust declined', 'Nothing changed', 'Only trust declined'], answer: 1 },
      ],
    },
    quiz: [
      { type: 'mc', question: "Seldom ___ such dedication.", options: ['I have seen', 'have I seen', 'I saw', 'did I saw'], answer: 1 },
      { type: 'mc', question: "Not only ___ late, but he also forgot the report.", options: ['he arrived', 'did he arrive', 'he did arrive', 'arrived he'], answer: 1 },
      { type: 'fill', question: "Under no circumstances ___ (should/you) sign this.", answer: 'should you' },
      { type: 'mc', question: "'notwithstanding' is closest to...", options: ['because of', 'despite', 'due to', 'thanks to'], answer: 1 },
      { type: 'mc', question: "'to undermine' means...", options: ['fortalecer', 'socavar', 'ignorar', 'demostrar'], answer: 1 },
      { type: 'fill', question: "No sooner ___ (they/leave) than it started raining.", answer: 'had they left' },
      { type: 'mc', question: "'compelling' means...", options: ['aburrido', 'convincente', 'confuso', 'irrelevante'], answer: 1 },
      { type: 'mc', question: "'to hinge on' means...", options: ['depender de', 'oponerse a', 'ignorar', 'confirmar'], answer: 0 },
    ],
  },
  {
    id: 'C1-u2',
    level: 'C1',
    order: 2,
    title: 'Business and Negotiation',
    subtitle: 'Advanced modals & hedging language',
    vocabulary: [
      { word: 'to leverage', translation: 'aprovechar / apalancar', example: 'We should leverage our existing network.' },
      { word: 'to be inclined to', translation: 'estar inclinado a', example: "I'm inclined to accept the offer." },
      { word: 'trade-off', translation: 'compensación / contrapartida', example: 'There is a trade-off between speed and quality.' },
      { word: 'to concede ground', translation: 'ceder terreno', example: "We might have to concede ground on price." },
      { word: 'a stretch', translation: 'algo exagerado / difícil de lograr', example: 'That target seems like a stretch.' },
      { word: 'to hedge', translation: 'cubrirse / matizar', example: 'She hedged her answer to avoid commitment.' },
      { word: 'bottom line', translation: 'resultado final / lo esencial', example: 'The bottom line is that we need more time.' },
      { word: 'to be on the same page', translation: 'estar de acuerdo / alineados', example: "Let's make sure we're on the same page." },
      { word: 'contingency', translation: 'contingencia / plan B', example: 'We need a contingency plan.' },
      { word: 'to iron out', translation: 'resolver / pulir detalles', example: 'We still need to iron out the details.' },
    ],
    grammar: {
      title: 'Advanced Modals & Hedging',
      explanation:
        "En contextos profesionales, usamos lenguaje matizado ('hedging') para sonar menos directos: 'It could be argued that...', 'We might want to consider...', 'This may not be entirely accurate.' Modales como 'could', 'might', 'may well' suavizan afirmaciones, mientras que 'would' se usa para propuestas corteses: 'Would it be possible to...?'",
      examples: [
        "It could be argued that the risk outweighs the benefit.",
        "We might want to reconsider the timeline.",
        "This may well be the best option available.",
        "Would you be able to send the figures by Friday?",
        "I'd tend to agree, although there are exceptions.",
      ],
    },
    dialogue: {
      title: 'Contract Negotiation',
      lines: [
        { speaker: 'Client', text: "We'd be inclined to sign, provided the price comes down slightly." },
        { speaker: 'Vendor', text: "I understand. There might be some room to negotiate on volume discounts." },
        { speaker: 'Client', text: "That would help. What's the bottom line for a two-year contract?" },
        { speaker: 'Vendor', text: "Let me iron out the details with my team and get back to you tomorrow." },
        { speaker: 'Client', text: "Sounds fair. We just want to make sure we're on the same page on delivery times." },
        { speaker: 'Vendor', text: "Understood. We'll leverage our logistics partner to guarantee that." },
      ],
      comprehension: [
        { question: "What does the client want in order to sign?", options: ['A longer contract', 'A lower price', 'Faster delivery', 'More meetings'], answer: 1 },
        { question: "What will the vendor do to guarantee delivery times?", options: ['Hire more staff', 'Leverage their logistics partner', 'Lower the price', 'Extend the deadline'], answer: 1 },
      ],
    },
    quiz: [
      { type: 'mc', question: "It ___ (could/argue) that the plan is too risky.", options: ['could argue', 'could be argued', 'can argued', 'could arguing'], answer: 1 },
      { type: 'mc', question: "'Would it be possible to...' is used to...", options: ['dar una orden', 'pedir algo cortésmente', 'negarse', 'quejarse'], answer: 1 },
      { type: 'fill', question: "We still need to ___ (resolver detalles) the contract.", answer: 'iron out' },
      { type: 'mc', question: "'trade-off' means...", options: ['ganancia total', 'compensación entre dos cosas', 'pérdida total', 'acuerdo firmado'], answer: 1 },
      { type: 'mc', question: "'to be on the same page' means...", options: ['estar en desacuerdo', 'estar alineados', 'estar confundidos', 'estar ocupados'], answer: 1 },
      { type: 'fill', question: "That target seems like ___ (algo difícil de lograr).", answer: 'a stretch' },
      { type: 'mc', question: "'to leverage' means...", options: ['ignorar', 'aprovechar', 'rechazar', 'reducir'], answer: 1 },
      { type: 'mc', question: "'bottom line' means...", options: ['lo esencial / resultado final', 'la primera línea', 'un detalle menor', 'el título'], answer: 0 },
    ],
  },
  {
    id: 'C1-u3',
    level: 'C1',
    order: 3,
    title: 'Cause, Effect and Contrast',
    subtitle: 'Advanced linking words',
    vocabulary: [
      { word: 'consequently', translation: 'en consecuencia', example: 'Sales dropped; consequently, they cut costs.' },
      { word: 'whereas', translation: 'mientras que', example: 'He prefers tea, whereas she prefers coffee.' },
      { word: 'given that', translation: 'dado que', example: 'Given that it was raining, we stayed in.' },
      { word: 'nevertheless', translation: 'sin embargo / no obstante', example: 'It was expensive; nevertheless, we bought it.' },
      { word: 'as a result of', translation: 'como resultado de', example: 'As a result of the delay, we missed the flight.' },
      { word: 'albeit', translation: 'aunque / si bien', example: 'The plan worked, albeit slowly.' },
      { word: 'in light of', translation: 'a la luz de / dado', example: 'In light of the new evidence, they changed their view.' },
      { word: 'on the grounds that', translation: 'basándose en que', example: 'They rejected it on the grounds that it was too costly.' },
      { word: 'thereby', translation: 'de ese modo', example: 'They automated the process, thereby saving time.' },
      { word: 'conversely', translation: 'por el contrario', example: 'Prices rose; conversely, demand fell.' },
    ],
    grammar: {
      title: 'Advanced Linking Words (causa, efecto, contraste)',
      explanation:
        "En textos formales usamos conectores precisos: causa ('given that', 'on the grounds that', 'as a result of'), consecuencia ('consequently', 'thereby'), contraste ('whereas', 'nevertheless', 'conversely', 'albeit'). 'Albeit' suele ir seguido de un adjetivo o frase corta: 'a good plan, albeit risky.'",
      examples: [
        "Given that the budget is limited, we must prioritize.",
        "The results were positive, albeit modest.",
        "Consequently, the company revised its strategy.",
        "He supports the reform, whereas his colleague opposes it.",
        "They automated the workflow, thereby reducing errors.",
      ],
    },
    dialogue: {
      title: 'Quarterly Review',
      lines: [
        { speaker: 'Director', text: "Given that revenue fell last quarter, what do you propose?" },
        { speaker: 'Analyst', text: "We should cut discretionary spending, thereby protecting our margins." },
        { speaker: 'Director', text: "Nevertheless, we can't cut marketing entirely." },
        { speaker: 'Analyst', text: "Agreed. Whereas marketing needs investment, operations can be trimmed." },
        { speaker: 'Director', text: "And on the grounds that competitors are also struggling, we might have room to adjust." },
        { speaker: 'Analyst', text: "Exactly — the results were disappointing, albeit not disastrous." },
      ],
      comprehension: [
        { question: 'What does the analyst propose?', options: ['Cutting marketing entirely', 'Cutting discretionary spending', 'Increasing all budgets', 'Firing staff'], answer: 1 },
        { question: 'How does the analyst describe the results?', options: ['Disastrous', 'Excellent', 'Disappointing but not disastrous', 'Irrelevant'], answer: 2 },
      ],
    },
    quiz: [
      { type: 'mc', question: "___ the delay, we missed the connection.", options: ['As a result of', 'Whereas', 'Albeit', 'Conversely'], answer: 0 },
      { type: 'mc', question: "He supports it, ___ his partner opposes it.", options: ['consequently', 'whereas', 'given that', 'thereby'], answer: 1 },
      { type: 'fill', question: "The plan worked, ___ (aunque) slowly.", answer: 'albeit' },
      { type: 'mc', question: "'in light of' means...", options: ['a pesar de', 'dado / a la luz de', 'en lugar de', 'sin importar'], answer: 1 },
      { type: 'mc', question: "'thereby' means...", options: ['sin embargo', 'de ese modo', 'por el contrario', 'mientras tanto'], answer: 1 },
      { type: 'fill', question: "They rejected it ___ (basándose en que) it was too risky.", answer: 'on the grounds that' },
      { type: 'mc', question: "'conversely' means...", options: ['de igual manera', 'por el contrario', 'en consecuencia', 'dado que'], answer: 1 },
      { type: 'mc', question: "Correct: 'Costs rose; ___, profits declined.'", options: ['whereas', 'consequently', 'given that', 'albeit'], answer: 1 },
    ],
  },
  {
    id: 'C1-u4',
    level: 'C1',
    order: 4,
    title: 'Idiomatic English',
    subtitle: 'Common idioms and collocations',
    vocabulary: [
      { word: 'to hit the ground running', translation: 'empezar con mucha energía/eficacia', example: 'The new hire hit the ground running.' },
      { word: 'to be on the fence', translation: 'estar indeciso', example: "I'm still on the fence about the offer." },
      { word: 'to cut corners', translation: 'ahorrar esfuerzo/dinero de forma poco cuidadosa', example: 'They cut corners on quality control.' },
      { word: 'a game changer', translation: 'algo que lo cambia todo', example: 'This technology is a real game changer.' },
      { word: 'to read between the lines', translation: 'leer entre líneas', example: 'You have to read between the lines here.' },
      { word: 'to bite the bullet', translation: 'aguantarse / afrontar algo difícil', example: 'We finally bit the bullet and raised prices.' },
      { word: 'to touch base', translation: 'ponerse en contacto brevemente', example: "Let's touch base next week." },
      { word: 'a blessing in disguise', translation: 'una bendición disfrazada', example: 'Losing that job was a blessing in disguise.' },
      { word: 'to go the extra mile', translation: 'esforzarse más de lo necesario', example: 'She always goes the extra mile for clients.' },
      { word: 'to be in the loop', translation: 'estar informado / al tanto', example: 'Please keep me in the loop.' },
    ],
    grammar: {
      title: 'Idioms and Collocations en contexto profesional',
      explanation:
        "Los hablantes nativos usan expresiones idiomáticas con frecuencia en contextos informales y semi-formales. Es clave entender su significado figurado (no literal) y saber en qué registro son apropiadas. Muchas funcionan como verbos con partícula o frases fijas y no se pueden traducir palabra por palabra.",
      examples: [
        "She hit the ground running in her new role.",
        "I'm on the fence about accepting the promotion.",
        "Let's touch base once you have the numbers.",
        "It felt like a setback, but it was a blessing in disguise.",
        "He always goes the extra mile to help the team.",
      ],
    },
    dialogue: {
      title: 'Catching Up',
      lines: [
        { speaker: 'Nate', text: "How's the new job going?" },
        { speaker: 'Priya', text: "Great, actually. I hit the ground running from day one." },
        { speaker: 'Nate', text: "That's awesome. Any downsides?" },
        { speaker: 'Priya', text: "A few — the team sometimes cuts corners to meet deadlines." },
        { speaker: 'Nate', text: "That's rough. Are you thinking of staying long-term?" },
        { speaker: 'Priya', text: "I'm still a bit on the fence, but overall it feels like a game changer for my career." },
      ],
      comprehension: [
        { question: 'How did Priya start her new job?', options: ['Slowly and carefully', 'She hit the ground running', 'She was on the fence', 'She cut corners'], answer: 1 },
        { question: 'What downside does Priya mention?', options: ['Low salary', 'The team cuts corners', 'Long commute', 'No teamwork'], answer: 1 },
      ],
    },
    quiz: [
      { type: 'mc', question: "'to hit the ground running' means...", options: ['empezar con mucha energía', 'llegar tarde', 'rendirse', 'descansar'], answer: 0 },
      { type: 'mc', question: "'to be on the fence' means...", options: ['estar seguro', 'estar indeciso', 'estar ocupado', 'estar enfadado'], answer: 1 },
      { type: 'fill', question: "They ___ ___ ___ (ahorraron esfuerzo indebidamente) on safety checks.", answer: 'cut corners' },
      { type: 'mc', question: "'a blessing in disguise' means...", options: ['una mala noticia', 'algo malo que resulta bueno', 'un regalo caro', 'una sorpresa desagradable'], answer: 1 },
      { type: 'mc', question: "'to touch base' means...", options: ['discutir acaloradamente', 'ponerse en contacto brevemente', 'terminar una relación', 'firmar un contrato'], answer: 1 },
      { type: 'fill', question: "Please keep me ___ ___ ___ (al tanto).", answer: 'in the loop' },
      { type: 'mc', question: "'to go the extra mile' means...", options: ['rendirse antes', 'esforzarse más de lo necesario', 'llegar tarde', 'trabajar menos'], answer: 1 },
      { type: 'mc', question: "'a game changer' means...", options: ['algo irrelevante', 'algo que lo cambia todo', 'un juego nuevo', 'un error grave'], answer: 1 },
    ],
  },
];

export function getUnitById(id) {
  return COURSE.find((u) => u.id === id);
}

export function getOrderedUnits() {
  const levelOrder = LEVELS.map((l) => l.id);
  return [...COURSE].sort((a, b) => {
    const lvl = levelOrder.indexOf(a.level) - levelOrder.indexOf(b.level);
    if (lvl !== 0) return lvl;
    return a.order - b.order;
  });
}
